include: package:lint/analysis_options.yaml

linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #
    
    # Use parameter order as in json response
    sort_pub_dependencies: false

    # these should be removed they slow down dev
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    avoid_print: false
    